"use client";

import { useState, type FormEvent } from "react";
import { useClinic } from "../clinic-provider";
import type { AppointmentStatus, CaseStatus, CaseType, DentalCase, Patient } from "../types";
import { Button, Card, EmptyState, Field, Icon, inputClass, Modal, StatusBadge } from "./ui";
import { PageHeader } from "./portal-shell";

const today = () => new Date().toISOString().slice(0, 10);
const caseTypes: CaseType[] = ["Filling", "Extraction", "Root Canal", "Crown", "Orthodontics", "Cleaning", "Whitening", "Other"];

export function DoctorPortal({ section }: { section: string }) {
  if (section === "patients") return <DoctorPatients />;
  if (section === "cases") return <CasesView />;
  return <DoctorDashboard />;
}

function DoctorDashboard() {
  const { data, setAppointmentStatus } = useClinic(); const [patient, setPatient] = useState<Patient | null>(null); const [casePatient, setCasePatient] = useState<Patient | null>(null);
  if (!data) return null; const doctor=data.doctors[0]; const rows=data.appointments.filter(a=>a.doctorId===doctor.id&&a.date===today()&&a.status!=="Cancelled").sort((a,b)=>a.time.localeCompare(b.time)); const current=rows.find(a=>a.status==="In Progress"); const waiting=rows.filter(a=>a.status==="Checked In");
  return <><PageHeader eyebrow={doctor.specialty} title="Today’s clinical desk" description="See the live queue, open patient history, and keep each visit moving."/><div className="grid gap-4 sm:grid-cols-3"><Metric label="Appointments" value={rows.length} icon="calendar"/><Metric label="Waiting" value={waiting.length} icon="clock"/><Metric label="Completed" value={rows.filter(a=>a.status==="Completed").length} icon="check"/></div>
    {current&&<Card className="mt-6 overflow-hidden border-[#8dbdc1]"><div className="bg-[#176b73] px-5 py-3 text-xs font-bold uppercase tracking-[.14em] text-white/75">Current patient</div><div className="flex flex-col gap-5 p-5 sm:flex-row sm:items-center"><PatientIdentity id={current.patientId}/><div className="flex-1"><p className="text-sm font-bold">{current.reason}</p><p className="mt-1 text-xs text-slate-500">Started · {current.time} · {current.duration} minutes</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>setPatient(data.patients.find(p=>p.id===current.patientId)??null)}>History</Button><Button onClick={()=>setCasePatient(data.patients.find(p=>p.id===current.patientId)??null)}>Add dental case</Button><Button variant="secondary" onClick={()=>setAppointmentStatus(current.id,"Completed")}>Complete visit</Button></div></div></Card>}
    <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_1fr]"><Queue title="Waiting patients" empty="No patients are waiting." rows={waiting} action={(id)=>setAppointmentStatus(id,"In Progress")} actionLabel="Start visit" onPatient={setPatient}/><Queue title="Upcoming patients" empty="No more appointments today." rows={rows.filter(a=>a.status==="Scheduled")} action={(id)=>setAppointmentStatus(id,"Checked In")} actionLabel="Mark arrived" onPatient={setPatient}/></div>
    {patient&&<DoctorPatientDetail patient={patient} onClose={()=>setPatient(null)} onCase={()=>{setCasePatient(patient);setPatient(null)}}/>}{casePatient&&<CaseForm patient={casePatient} onClose={()=>setCasePatient(null)}/>}</>;
}
function Metric({label,value,icon}:{label:string;value:number;icon:string}){return <Card className="flex items-center gap-4 p-5"><span className="rounded-xl bg-teal-50 p-3 text-teal-700"><Icon name={icon}/></span><div><p className="text-2xl font-extrabold">{value}</p><p className="text-sm font-semibold text-slate-500">{label}</p></div></Card>}
function PatientIdentity({id}:{id:string}){const{data}=useClinic();const p=data?.patients.find(x=>x.id===id);return <div className="flex min-w-0 items-center gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-teal-50 text-sm font-bold text-teal-700">{p?.name.split(" ").map(v=>v[0]).slice(0,2)}</span><div className="min-w-0"><b className="block truncate">{p?.name}</b><span className="text-xs text-slate-500">{p?.phone}</span></div></div>}
function Queue({title,empty,rows,action,actionLabel,onPatient}:{title:string;empty:string;rows:{id:string;patientId:string;time:string;reason:string;status:AppointmentStatus}[];action(id:string):void;actionLabel:string;onPatient(p:Patient):void}){const{data}=useClinic();return <Card><div className="border-b border-slate-100 p-5"><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs text-slate-500">{rows.length} in this list</p></div>{rows.length?<div className="divide-y divide-slate-100">{rows.map(a=><div key={a.id} className="p-4"><div className="flex items-center justify-between gap-3"><button className="min-w-0 text-left" onClick={()=>{const p=data?.patients.find(p=>p.id===a.patientId);if(p)onPatient(p)}}><PatientIdentity id={a.patientId}/></button><b className="text-sm">{a.time}</b></div><p className="ml-14 mt-1 text-xs text-slate-500">{a.reason}</p><div className="ml-14 mt-3 flex gap-2"><Button className="min-h-8 px-3 py-1 text-xs" onClick={()=>action(a.id)}>{actionLabel}</Button><Button variant="ghost" className="min-h-8 px-3 py-1 text-xs" onClick={()=>{const p=data?.patients.find(p=>p.id===a.patientId);if(p)onPatient(p)}}>Open history</Button></div></div>)}</div>:<EmptyState title={empty} description="The list will update as Reception changes appointment status."/>}</Card>}

function DoctorPatients(){const{data}=useClinic();const[q,setQ]=useState("");const[selected,setSelected]=useState<Patient|null>(null);const[casePatient,setCasePatient]=useState<Patient|null>(null);if(!data)return null;const patients=data.patients.filter(p=>`${p.name} ${p.phone}`.toLowerCase().includes(q.toLowerCase()));return <><PageHeader eyebrow="Clinical records" title="Patients" description="Open patient details, review visit history, and manage simple dental cases."/><Card><div className="border-b border-slate-100 p-4"><div className="relative"><Icon name="search" className="absolute left-3 top-3 h-5 w-5 text-slate-400"/><input className={`${inputClass} pl-10`} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search patients…"/></div></div><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{patients.map(p=><button key={p.id} onClick={()=>setSelected(p)} className="rounded-xl border border-slate-100 p-4 text-left transition hover:border-teal-200 hover:bg-teal-50/30"><PatientIdentity id={p.id}/><div className="mt-4 flex justify-between text-xs text-slate-500"><span>{data.appointments.filter(a=>a.patientId===p.id).length} appointments</span><span>{data.cases.filter(c=>c.patientId===p.id).length} cases</span></div></button>)}</div></Card>{selected&&<DoctorPatientDetail patient={selected} onClose={()=>setSelected(null)} onCase={()=>{setCasePatient(selected);setSelected(null)}}/>}{casePatient&&<CaseForm patient={casePatient} onClose={()=>setCasePatient(null)}/>}</>}
function DoctorPatientDetail({patient,onClose,onCase}:{patient:Patient;onClose():void;onCase():void}){const{data}=useClinic();if(!data)return null;const cases=data.cases.filter(c=>c.patientId===patient.id).sort((a,b)=>b.createdDate.localeCompare(a.createdDate));return <Modal title={patient.name} description={`${patient.phone} · ${patient.email}`} onClose={onClose} wide><div className="rounded-xl bg-amber-50 p-4"><p className="text-xs font-bold uppercase text-amber-700">Medical notes</p><p className="mt-1 text-sm text-amber-950">{patient.medicalNotes||"No medical notes"}</p></div><div className="mb-3 mt-6 flex items-center justify-between"><h3 className="font-bold">Dental case history</h3><Button className="min-h-9" onClick={onCase}><Icon name="plus" className="h-4 w-4"/>New case</Button></div>{cases.length?<div className="space-y-3">{cases.map(c=><div key={c.id} className="rounded-xl border border-slate-100 p-4"><div className="flex justify-between"><b>{c.type}</b><StatusBadge status={c.status}/></div><p className="mt-2 text-sm leading-6 text-slate-600">{c.notes}</p><p className="mt-2 text-xs text-slate-400">Created {c.createdDate}{c.completedDate?` · Completed ${c.completedDate}`:""}</p></div>)}</div>:<EmptyState title="No dental cases" description="Create a simple case when clinical work begins."/>}</Modal>}

function CasesView(){const{data,editCase}=useClinic();const[q,setQ]=useState("");const[status,setStatus]=useState("All");const[editing,setEditing]=useState<DentalCase|null>(null);const[creating,setCreating]=useState<Patient|null>(null);if(!data)return null;const rows=data.cases.filter(c=>{const p=data.patients.find(p=>p.id===c.patientId);return `${p?.name} ${c.type} ${c.notes}`.toLowerCase().includes(q.toLowerCase())&&(status==="All"||c.status===status)});return <><PageHeader eyebrow="Simple clinical workflow" title="Dental cases" description="Create, update, and complete focused dental cases without complex charts or treatment plans." action={<Button onClick={()=>setCreating(data.patients[0])}><Icon name="plus"/>New case</Button>}/><Card><div className="grid gap-3 border-b border-slate-100 p-4 sm:grid-cols-[1fr_180px]"><input className={inputClass} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search patient, type, or notes…"/><select className={inputClass} value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Open</option><option>In Progress</option><option>Completed</option></select></div>{rows.length?<div className="divide-y divide-slate-100">{rows.map(c=><div key={c.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><b>{c.type}</b><StatusBadge status={c.status}/></div><p className="mt-1 text-sm text-slate-600">{data.patients.find(p=>p.id===c.patientId)?.name}</p><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{c.notes}</p></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>setEditing(c)}>Edit</Button>{c.status!=="Completed"&&<Button onClick={()=>editCase({...c,status:"Completed",completedDate:today()})}>Complete</Button>}</div></div>)}</div>:<EmptyState title="No matching cases" description="Try a different search or create a new dental case."/>}</Card>{editing&&<CaseForm patient={data.patients.find(p=>p.id===editing.patientId)!} item={editing} onClose={()=>setEditing(null)}/>} {creating&&<CaseForm patient={creating} choosePatient onClose={()=>setCreating(null)}/>}</>}

function CaseForm({patient,item,choosePatient=false,onClose}:{patient:Patient;item?:DentalCase;choosePatient?:boolean;onClose():void}){const{data,addCase,editCase}=useClinic();const[patientId,setPatientId]=useState(patient.id);const[type,setType]=useState<CaseType>(item?.type??"Filling");const[notes,setNotes]=useState(item?.notes??"");const[status,setStatus]=useState<CaseStatus>(item?.status??"Open");const[error,setError]=useState("");function submit(e:FormEvent){e.preventDefault();if(notes.trim().length<5){setError("Add clear clinical notes (at least 5 characters).");return;}if(item)editCase({...item,patientId,type,notes,status,completedDate:status==="Completed"?(item.completedDate??today()):undefined});else addCase({patientId,doctorId:data!.doctors[0].id,type,notes,status});onClose();}return <Modal title={item?"Edit dental case":"Create dental case"} description="Keep the record concise: type, notes, status, and dates." onClose={onClose}><form onSubmit={submit} className="space-y-4">{choosePatient?<Field label="Patient"><select className={inputClass} value={patientId} onChange={e=>setPatientId(e.target.value)}>{data?.patients.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>:<div className="rounded-xl bg-slate-50 p-3 text-sm font-bold">{patient.name}</div>}<Field label="Case type"><select className={inputClass} value={type} onChange={e=>setType(e.target.value as CaseType)}>{caseTypes.map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Clinical notes *" error={error}><textarea className={`${inputClass} min-h-32 py-3`} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Findings and concise case notes…"/></Field><Field label="Status"><select className={inputClass} value={status} onChange={e=>setStatus(e.target.value as CaseStatus)}><option>Open</option><option>In Progress</option><option>Completed</option></select></Field><div className="flex justify-end gap-3"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit">{item?"Save case":"Create case"}</Button></div></form></Modal>}
